import 'package:flutter/material.dart';

const supabaseAnonKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4cnlkYXl1dnd4cmFwZWpuYXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4MDEzMjQsImV4cCI6MjA5NTM3NzMyNH0.orPAOSlUCmHm0u3jtG0aRsZq2uaH_ny_pFIUXOD7IJ8';

final themeModeNotifier = ValueNotifier<ThemeMode>(ThemeMode.light);
final languageNotifier = ValueNotifier<String>('es');

const Map<String, Map<String, String>> translations = {
  'es': {
    'appTitle': 'Gestor de Suscripciones',
    'welcomeBack': 'Bienvenido de nuevo',
    'loginInstructions':
        'Introduce tu correo electrónico y contraseña para iniciar sesión',
    'registerInstructions': 'Introduce tus datos para crear una cuenta',
    'signUp': 'Registrarse',
    'nameLabel': 'Nombre completo',
    'regionLabel': 'Configuración regional (ej: es-ES)',
    'timezoneLabel': 'Zona horaria (ej: Europe/Madrid)',
    'createAccount': 'Crear cuenta',
    'alreadyHaveAccount': '¿Ya tienes una cuenta? Inicia sesión',
    'noAccount': '¿No tienes una cuenta? Regístrate',
    'nameRequired': 'Por favor, introduce tu nombre',
    'regionRequired': 'Por favor, introduce la configuración regional',
    'timezoneRequired': 'Por favor, introduce la zona horaria',
    'registerSuccess': 'Cuenta creada con éxito. Ahora puedes iniciar sesión.',
    'emailLabel': 'Correo electrónico',
    'passwordLabel': 'Contraseña',
    'rememberMe': 'Recordarme',
    'signIn': 'Iniciar sesión',
    'forgotPassword': '¿Olvidaste tu contraseña?',
    'emailRequired': 'Por favor, introduce tu correo electrónico',
    'invalidEmail': 'Introduce una dirección de correo electrónico válida',
    'passwordRequired': 'Por favor, introduce tu contraseña',
    'passwordMinLength': 'La contraseña debe tener al menos 6 caracteres',
    'supabaseNotConfigured':
        'Supabase anonym key no configurada. Asigna _supabaseAnonKey en lib/main.dart.',
    'loginSuccess': 'Sesión iniciada como {displayName}',
    'loginError': 'Error al iniciar sesión: ({statusCode}): {errorMessage}',
    'networkError': 'Error de red: {error}',
    'sessionClosed':
        'Tu sesión ha sido cerrada, por favor inicia sesión de nuevo',
    'deleteSubscription': 'Eliminar suscripción',
    'deleteConfirmationTitle': 'Eliminar suscripción',
    'deleteConfirmationMessage':
        '¿Estás seguro de que deseas eliminar esta suscripción?',
    'cancel': 'Cancelar',
    'delete': 'Eliminar',
    'deletionSuccess': 'Suscripción eliminada con éxito',
    'subscriptionNotFound': 'Suscripción no encontrada',
    'deletionFailed': 'No se pudo eliminar la suscripción',
    'deletePaymentMethod': 'Eliminar método de pago',
    'deletePaymentMethodConfirmationTitle': 'Eliminar método de pago',
    'deletePaymentMethodConfirmationMessage': '¿Estás seguro de que deseas eliminar este método de pago?',
    'paymentMethodDeletionSuccess': 'Método de pago eliminado con éxito',
    'paymentMethodNotFound': 'Método de pago no encontrado',
    'paymentMethodDeletionFailed': 'No se pudo eliminar el método de pago',
    'subscriptionsOf': 'Suscripciones de',
    'subscriptions': 'Suscripciones',
    'paymentMethods': 'Métodos de pago',
    'settings': 'Configuración',
    'logout': 'Cerrar sesión',
    'userLabel': 'Usuario',
    'emailLabelShort': 'Correo',
    'noSubscriptions': 'No hay suscripciones disponibles.',
    'monthlyTotalSpend': 'Gasto mensual (Activas)',
    'nextLabel': 'Próxima:',
    'chargeLabel': 'Cobro:',
    'trialEndLabel': 'Fin prueba:',
    'cancelLabel': 'Cancelar',
    'unknown': 'Desconocido',
    'lastDigits': 'Últimos dígitos',
    'newSubscription': 'Nueva suscripción',
    'addSubscription': 'Agregar nueva suscripción',
    'subscriptionCreated': 'Suscripción creada con éxito',
    'serviceLabel': 'Servicio',
    'monthlyCost': 'Costo mensual',
    'currencyLabel': 'Moneda',
    'billingCycle': 'Ciclo de facturación',
    'chargeDate': 'Fecha de cobro (YYYY-MM-DD)',
    'nextChargeDate': 'Próxima fecha de cobro (YYYY-MM-DD)',
    'trialEnd': 'Fin de prueba (opcional)',
    'status': 'Estado',
    'cancellationUrl': 'URL de cancelación',
    'paymentMethodLabel': 'Método de pago',
    'paymentMethodRequired': 'Selecciona un método de pago',
    'addPaymentMethod': 'Agregar método de pago',
    'createPaymentMethod': 'Crear método de pago',
    'editPaymentMethod': 'Editar método de pago',
    'editPaymentMethodSuccess': 'Método de pago editado con éxito',
    'paymentMethodType': 'Tipo de método',
    'paymentMethodName': 'Nombre del método',
    'paymentMethodNameHint': 'Nombre opcional para este método',
    'referenceToken': 'Token de referencia',
    'referenceTokenRequired': 'Introduce el token de referencia',
    'last4': 'Últimos 4 dígitos',
    'last4Required': 'Introduce los últimos 4 dígitos',
    'last4Invalid': 'Introduce exactamente 4 dígitos',
    'expirationDate': 'Fecha de expiración',
    'expirationMonth': 'Mes expiración',
    'expirationYear': 'Año expiración',
    'expirationMonthRequired': 'Introduce el mes de expiración',
    'expirationMonthInvalid': 'Introduce un mes válido (1-12)',
    'expirationYearRequired': 'Introduce el año de expiración',
    'expirationYearInvalid': 'Introduce un año válido',
    'defaultPaymentMethod': 'Predeterminado',
    'paymentMethodCreated': 'Método de pago creado con éxito',
    'creditCard': 'Tarjeta de crédito',
    'debitCard': 'Tarjeta de débito',
    'paypal': 'PayPal',
    'bankTransfer': 'Transferencia bancaria',
    'other': 'Otro',
    'serviceRequired': 'Introduce el nombre del servicio',
    'costRequired': 'Introduce el costo mensual',
    'invalidNumber': 'Introduce un número válido',
    'currencyRequired': 'Introduce la moneda',
    'billingCycleRequired': 'Introduce el ciclo de facturación',
    'chargeDateRequired': 'Introduce la fecha de cobro',
    'nextChargeDateRequired': 'Introduce la próxima fecha de cobro',
    'statusRequired': 'Introduce el estado',
    'selectCategory': 'Seleccionar categoría',
    'createSubscription': 'Crear suscripción',
    'editSubscription': 'Editar suscripción',
    'editSuccess': 'Suscripción editada con éxito',
    'noPaymentMethods': 'No hay métodos de pago disponibles.',
    'language': 'Idioma',
    'spanish': 'Español',
    'english': 'English',
    'theme': 'Tema',
    'light': 'Claro',
    'dark': 'Oscuro',
    'system': 'Sistema',
    'subscriptionsDrawer': 'Suscripciones',
    'paymentMethodsDrawer': 'Métodos de pago',
    'settingsDrawer': 'Configuración',
    'logoutDrawer': 'Cerrar sesión',
    'addNewSubscription': 'Agregar nueva suscripción',
    'aboutUsDrawer': 'Sobre nosotros',
    'aboutUsMessage': 'Desarrollado por Diego Sañudo Rodriguez.\n\nEste proyecto es un gestor de suscripciones multiplataforma diseñado para facilitar el control de tus gastos mensuales.',
    'serviceName': 'Servicio',
    'sortSubscriptions': 'Ordenar suscripciones',
    'sortNearPayment': 'Próximos pagos primero',
    'sortHighestPrice': 'Precio más alto primero',
    'sortLowestPrice': 'Precio más bajo primero',
    'sortAlphabetical': 'Orden alfabético',
    'noPaymentMethodsAvailable': 'No hay métodos de pago disponibles.',
  },
  'en': {
    'appTitle': 'Subscription Manager',
    'welcomeBack': 'Welcome back',
    'loginInstructions': 'Enter your email and password to sign in',
    'registerInstructions': 'Enter your details to create an account',
    'signUp': 'Sign up',
    'nameLabel': 'Full Name',
    'regionLabel': 'Regional settings (e.g., en-US)',
    'timezoneLabel': 'Timezone (e.g., America/New_York)',
    'createAccount': 'Create account',
    'alreadyHaveAccount': 'Already have an account? Sign in',
    'noAccount': 'Don\'t have an account? Sign up',
    'nameRequired': 'Please enter your name',
    'regionRequired': 'Please enter the regional settings',
    'timezoneRequired': 'Please enter the timezone',
    'registerSuccess': 'Account created successfully. You can now sign in.',
    'emailLabel': 'Email',
    'passwordLabel': 'Password',
    'rememberMe': 'Remember me',
    'signIn': 'Sign in',
    'forgotPassword': 'Forgot your password?',
    'emailRequired': 'Please enter your email',
    'invalidEmail': 'Enter a valid email address',
    'passwordRequired': 'Please enter your password',
    'passwordMinLength': 'Password must be at least 6 characters',
    'supabaseNotConfigured':
        'Supabase anonym key not configured. Set _supabaseAnonKey in lib/main.dart.',
    'loginSuccess': 'Signed in as {displayName}',
    'loginError': 'Sign in error: ({statusCode}): {errorMessage}',
    'networkError': 'Network error: {error}',
    'sessionClosed': 'Your session has been closed, please log in again',
    'deleteSubscription': 'Delete subscription',
    'deleteConfirmationTitle': 'Delete subscription',
    'deleteConfirmationMessage':
        'Are you sure you want to delete this subscription?',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'deletionSuccess': 'Subscription deleted successfully',
    'subscriptionNotFound': 'Subscription not found',
    'deletionFailed': 'Could not delete subscription',
    'deletePaymentMethod': 'Delete payment method',
    'deletePaymentMethodConfirmationTitle': 'Delete payment method',
    'deletePaymentMethodConfirmationMessage': 'Are you sure you want to delete this payment method?',
    'paymentMethodDeletionSuccess': 'Payment method deleted successfully',
    'paymentMethodNotFound': 'Payment method not found',
    'paymentMethodDeletionFailed': 'Could not delete payment method',
    'subscriptionsOf': 'Subscriptions for',
    'subscriptions': 'Subscriptions',
    'paymentMethods': 'Payment Methods',
    'settings': 'Settings',
    'logout': 'Log out',
    'userLabel': 'User',
    'emailLabelShort': 'Email',
    'noSubscriptions': 'No subscriptions available.',
    'monthlyTotalSpend': 'Monthly spend (Active)',
    'nextLabel': 'Next:',
    'chargeLabel': 'Charge:',
    'trialEndLabel': 'Trial end:',
    'cancelLabel': 'Cancel',
    'unknown': 'Unknown',
    'lastDigits': 'Last digits',
    'newSubscription': 'New subscription',
    'addSubscription': 'Add new subscription',
    'createSubscription': 'Create subscription',
    'editSubscription': 'Edit subscription',
    'editSuccess': 'Subscription updated successfully',
    'subscriptionCreated': 'Subscription created successfully',
    'serviceLabel': 'Service',
    'monthlyCost': 'Monthly cost',
    'currencyLabel': 'Currency',
    'billingCycle': 'Billing cycle',
    'chargeDate': 'Charge date (YYYY-MM-DD)',
    'nextChargeDate': 'Next charge date (YYYY-MM-DD)',
    'trialEnd': 'Trial end (optional)',
    'status': 'Status',
    'cancellationUrl': 'Cancellation URL',
    'paymentMethodLabel': 'Payment method',
    'paymentMethodRequired': 'Please select a payment method',
    'addPaymentMethod': 'Add payment method',
    'createPaymentMethod': 'Create payment method',
    'editPaymentMethod': 'Edit payment method',
    'editPaymentMethodSuccess': 'Payment method updated successfully',
    'paymentMethodType': 'Payment method type',
    'paymentMethodName': 'Payment method name',
    'paymentMethodNameHint': 'Optional name for this method',
    'referenceToken': 'Reference token',
    'referenceTokenRequired': 'Please enter the reference token',
    'last4': 'Last 4 digits',
    'last4Required': 'Please enter the last 4 digits',
    'last4Invalid': 'Please enter exactly 4 digits',
    'expirationDate': 'Expiration date',
    'expirationMonth': 'Expiration month',
    'expirationYear': 'Expiration year',
    'expirationMonthRequired': 'Please enter the expiration month',
    'expirationMonthInvalid': 'Please enter a valid month (1-12)',
    'expirationYearRequired': 'Please enter the expiration year',
    'expirationYearInvalid': 'Please enter a valid year',
    'defaultPaymentMethod': 'Default payment method',
    'paymentMethodCreated': 'Payment method created successfully',
    'creditCard': 'Credit card',
    'debitCard': 'Debit card',
    'paypal': 'PayPal',
    'bankTransfer': 'Bank transfer',
    'other': 'Other',
    'serviceRequired': 'Please enter the service name',
    'costRequired': 'Please enter the monthly cost',
    'invalidNumber': 'Enter a valid number',
    'currencyRequired': 'Please enter the currency',
    'billingCycleRequired': 'Please enter the billing cycle',
    'chargeDateRequired': 'Please enter the charge date',
    'nextChargeDateRequired': 'Please enter the next charge date',
    'statusRequired': 'Please enter the status',
    'selectCategory': 'Select category',
    'noPaymentMethods': 'No payment methods available.',
    'language': 'Language',
    'spanish': 'Español',
    'english': 'English',
    'theme': 'Theme',
    'light': 'Light',
    'dark': 'Dark',
    'system': 'System',
    'subscriptionsDrawer': 'Subscriptions',
    'paymentMethodsDrawer': 'Payment Methods',
    'settingsDrawer': 'Settings',
    'logoutDrawer': 'Log out',
    'addNewSubscription': 'Add new subscription',
    'aboutUsDrawer': 'About Us',
    'aboutUsMessage': 'Developed by Diego Sañudo Rodriguez.\n\nThis project is a multi-platform subscription manager designed to help you easily track your monthly expenses.',
    'serviceName': 'Service',
    'sortSubscriptions': 'Sort subscriptions',
    'sortNearPayment': 'Nearest payments first',
    'sortHighestPrice': 'Highest price first',
    'sortLowestPrice': 'Lowest price first',
    'sortAlphabetical': 'Alphabetical order',
    'noPaymentMethodsAvailable': 'No payment methods available.',
  },
};